### ISSUE TITLE
Resolutions

### ISSUE THREAD

**Issue by OrangutanGaming** [ClintOxx/PUBG-Battlepoint-FarmBot#37]
Instead of using coordinates, you could use point values, where you get the size of the window, and multiply the size by a number less than 1. This would also work with windowed mode and resizing.

**Comment by peleon02** [comment]
If you can explain me more, I could try :smile:

**Comment by OrangutanGaming** [comment]
For example, https://github.com/OrangutanGaming/Warframe-Scripts/blob/master/warframeLogin.ahk uses it

**Comment by Cloxen** [comment]
interesting, hopefully ill get the chance to look into it soon
