### ISSUE TITLE
Afk bot does not start another game after exiting the previous one automatically

### ISSUE THREAD

**Issue by raykade** [ClintOxx/PUBG-Battlepoint-FarmBot#66]
The afk bot works fine and starts the first game but after a few minutes when it exits the game automatically it does not start another game and it stays in the lobby. how do i fix this ?

**Comment by peleon02** [comment]
output info pls

**Comment by raykade** [comment]
value error:not enough values to unpack (expected2,got 0)
this is what i see in the last line, before that there few other lines but second last line is 
file"location",line 31, in salir
c,d=y.split()

**Comment by peleon02** [comment]
Did you use the generator?

**Comment by peleon02** [comment]
If not check my repo

**Comment by raykade** [comment]
um.... no i just followed the instructions and i didnt see any mention of generator in it . Can you help me out with this?

**Comment by peleon02** [comment]
And follow the instructions

**Comment by peleon02** [comment]
Bots has been patched

**Comment by raykade** [comment]
Ah damn RIP =/ anything that can be done or you are gonna do in the future? just asking

**Comment by peleon02** [comment]
Keep thinking on fixes
